name: Deploy MkDocs to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        - run: pip install mkdocs
        - run: pip install mkdocs-material
        - run: pip install mkdocs-git-revision-date-localized-plugin
        - run: pip install mkdocs-git-authors-plugin
        - run: pip install mkdocs-git-committers-plugin-2
        - run: pip install markdown-callouts
        - run: pip install mkdocs-rss-plugin
        - run: pip install requests>=2.25.0
        - run: pip install python-dateutil>=2.8.0
        - run: pip install cachetools>=4.2.0
        - run: pip install python-dotenv>=0.19.0
        - run: pip install Pillow
        - run: pip install neoteroi-mkdocs

        - run: pip install mkdocs-document-dates==3.3
        - run: pip install pymdown-extensions
        - run: pip install mkdocs-material 
        - run: pip install --upgrade --force-reinstall mkdocs-material

        - run: pip install mkdocs-ai-summary-wcowin

      - name: Build MkDocs site
        run: mkdocs build

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          SOURCE: "site/"
          TARGET: "/var/www/MyNotebook"
