name: Deploy MkDocs to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install mkdocs
          pip install mkdocs-material
          pip install mkdocs-git-revision-date-localized-plugin
          pip install mkdocs-git-authors-plugin
          pip install mkdocs-git-committers-plugin-2
          pip install markdown-callouts
          pip install mkdocs-rss-plugin
          pip install requests>=2.25.0
          pip install python-dateutil>=2.8.0
          pip install cachetools>=4.2.0
          pip install python-dotenv>=0.19.0
          pip install Pillow
          pip install neoteroi-mkdocs
          pip install mkdocs-document-dates==3.3
          pip install pymdown-extensions
          pip install mkdocs-material 
          pip install --upgrade --force-reinstall mkdocs-material
          pip install mkdocs-ai-summary-wcowin

      - name: Build MkDocs site
        run: mkdocs build

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          SOURCE: "site/"
          TARGET: "/var/www/MyNotebook"
